FROM quay.io/keycloak/keycloak:26.0.5

# Copy realm configuration
COPY ./configs/keycloak/realm-config.json /opt/keycloak/data/import/

# Build optimized version and import realm during build
RUN /opt/keycloak/bin/kc.sh build \
    --db=postgres \
    --features=docker

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev", "--import-realm"]