web-client:
  type: public
  name: web client
  description: client Frontend
  redirect_uris:
    - 'http://localhost:5173/*'
  origins:
    - '*'
  logout_redirect: 'http://localhost:5173'

backend-client:
  type: private
  name: Backend Service
  description: Backend API Service
  redirect_uris:
    - 'http://localhost:8080/*'
  origins:
    - 'http://localhost:8080'
  root_url: 'http://localhost:8080/'
  admin_url: 'http://localhost:8080'
  authorization:
    roles:
      - worker
    scopes:
      - view
      - create
      - update
      - delete
    resources:
      - name: asset-resource
        type: base
        permissions:
          worker:
            - view
      - name: user-resource
        type: base
        permissions:
          worker:
            - view
      - name: admin-resource
        type: base