web-client:
  type: public
  client_id: vue-client
  name: web client
  description: client Frontend
  redirect_uris:
    - 'http://localhost:5173/*'
  origins:
    - '*'
  logout_redirect: 'http://localhost:5173'

backend-client:
  type: private
  name: Backend Service
  description: Backend API Service
  redirect_uris:
    - 'http://localhost:8080/*'
  origins:
    - 'http://localhost:8080'
  root_url: 'http://localhost:8080'
  admin_url: 'http://localhost:8080'

authorization:
  admin_group: base
  roles:
    - worker
  resources:
    asset-resource:
      name: asset
      type: base
      permissions:
        worker:
          - view
    measure-resource:
      name: measure
      type: base
      permissions:
        worker:
          - view
    dashboard-resource:
      name: dashboard
      type: base
      permissions:
        worker:
          - view
    widget-resource:
      name: widget
      type: base
      permissions:
        worker:
          - view
    device-resource:
      name: device
      type: base
    action-resource:
      name: action
      type: base
    alert-resource:
      name: alert
      type: base
    user-resource:
      name: user
      type: base
      permissions:
        worker:
          - view
    admin-resource:
      name: admin
      type: base
    role-resource:
      name: role
      type: base
    resource-resource:
      name: resource
      type: base
    scope-resource:
      name: scope
      type: base
